GestionIncidencias/Controllers/ExportarController.cs
namespace GestionIncidencias.Controllers
{
    public class ExportarController : Controller
    {
        private readonly ApplicationDbContext context;

        public ExportarController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            var incidencias = await context.Incidencias.ToListAsync();
            var incidenciasOrdenado = incidencias.OrderBy(i => i.FechaHora);
            int anyoMin = incidenciasOrdenado.First().FechaHora.Year;
            int anyoMax = incidenciasOrdenado.Last().FechaHora.Year;
            ViewBag.anyoMin = anyoMin;
            ViewBag.anyoMax = anyoMax;

            return View();
        }

        [HttpGet]
        public async Task<FileResult> ExportarExcelTodo()
        {

            var incidencias = await context.Incidencias.ToListAsync();
            var dispositivos = await context.Dispositivos.ToListAsync();
            var modelosDispositivos = await context.ModelosDispositivos.ToListAsync();
            var oficinas = await context.Oficinas.ToListAsync();
            var tecnicos = await context.Tecnicos.ToListAsync();
            var tiposDispositivos = await context.TiposDispositivos.ToListAsync();

            var incidenciasConsulta = from incidencia in incidencias
                                      join dispositivo in dispositivos on incidencia.DispositivoId equals dispositivo.Id
                                      join modelo in modelosDispositivos on dispositivo.ModeloDispositivoId equals modelo.Id
                                      join tipo in tiposDispositivos on modelo.TipoDispositivoId equals tipo.Id
                                      join oficina in oficinas on incidencia.OficinaId equals oficina.Id
                                      join tecnico in tecnicos on incidencia.TecnicoId equals tecnico.Id
                                      select new
                                      {
                                          incidencia,
                                          oficina,
                                          dispositivo,
                                          modelo,
                                          tipo,
                                          tecnico
                                      };

            var incidenciasExportar = incidenciasConsulta.Select(ic => new IncidenciaExportar()
            {
                Id = ic.incidencia.Id,
                FechaHora = ic.incidencia.FechaHora,
                Usuario = ic.incidencia.Usuario,
                CodOficina = ic.oficina.Codigo,
                NombreOficina = ic.oficina.Nombre,
                TipoDispositivo = ic.tipo.Titulo,
                ModeloDispositivo = ic.modelo.Marca + " " + ic.modelo.Modelo,
                Tecnico = ic.tecnico.NombreEmpresa,
                NumSerie = ic.dispositivo.NumeroSerie,
                Mensaje = ic.incidencia.Descripcion
            });

            var nombreArchivo = $"HistóricoAverías.xlsx";

            return GenerarExcel(nombreArchivo, incidenciasExportar);


        }

        public async Task<FileResult> ExportarExcelTodoSinDescripcion()
        {

            var incidencias = await context.Incidencias.ToListAsync();
            var dispositivos = await context.Dispositivos.ToListAsync();
            var modelosDispositivos = await context.ModelosDispositivos.ToListAsync();
            var oficinas = await context.Oficinas.ToListAsync();
            var tecnicos = await context.Tecnicos.ToListAsync();
            var tiposDispositivos = await context.TiposDispositivos.ToListAsync();

            var incidenciasConsulta = from incidencia in incidencias
                                      join dispositivo in dispositivos on incidencia.DispositivoId equals dispositivo.Id
                                      join modelo in modelosDispositivos on dispositivo.ModeloDispositivoId equals modelo.Id
                                      join tipo in tiposDispositivos on modelo.TipoDispositivoId equals tipo.Id
                                      join oficina in oficinas on incidencia.OficinaId equals oficina.Id
                                      join tecnico in tecnicos on incidencia.TecnicoId equals tecnico.Id
                                      select new
                                      {
                                          incidencia,
                                          oficina,
                                          dispositivo,
                                          modelo,
                                          tipo,
                                          tecnico
                                      };

            var incidenciasExportar = incidenciasConsulta.Select(ic => new IncidenciaExportar()
            {
                Id = ic.incidencia.Id,
                FechaHora = ic.incidencia.FechaHora,
                Usuario = ic.incidencia.Usuario,
                CodOficina = ic.oficina.Codigo,
                NombreOficina = ic.oficina.Nombre,
                TipoDispositivo = ic.tipo.Titulo,
                ModeloDispositivo = ic.modelo.Marca + " " + ic.modelo.Modelo,
                NumSerie = ic.dispositivo.NumeroSerie,
                Tecnico = ic.tecnico.NombreEmpresa
            });

            var nombreArchivo = $"HistóricoAverías.xlsx";

            return GenerarExcelSinDescripcion(nombreArchivo, incidenciasExportar);


        }

        public async Task<FileResult> ExportarExcelAnyo(string anyo)
        {
            int intAnyo = 0;
            int.TryParse(anyo, out intAnyo);

            var incidencias = await context.Incidencias.ToListAsync();
            var dispositivos = await context.Dispositivos.ToListAsync();
            var modelosDispositivos = await context.ModelosDispositivos.ToListAsync();
            var oficinas = await context.Oficinas.ToListAsync();
            var tecnicos = await context.Tecnicos.ToListAsync();
            var tiposDispositivos = await context.TiposDispositivos.ToListAsync();

            var incidenciasConsulta = from incidencia in incidencias
                                      join dispositivo in dispositivos on incidencia.DispositivoId equals dispositivo.Id
                                      join modelo in modelosDispositivos on dispositivo.ModeloDispositivoId equals modelo.Id
                                      join tipo in tiposDispositivos on modelo.TipoDispositivoId equals tipo.Id
                                      join oficina in oficinas on incidencia.OficinaId equals oficina.Id
                                      join tecnico in tecnicos on incidencia.TecnicoId equals tecnico.Id
                                      where incidencia.FechaHora.Year == intAnyo
                                      select new
                                      {
                                          incidencia,
                                          oficina,
                                          dispositivo,
                                          modelo,
                                          tipo,
                                          tecnico
                                      };

            var incidenciasExportar = incidenciasConsulta.Select(ic => new IncidenciaExportar()
            {
                Id = ic.incidencia.Id,
                FechaHora = ic.incidencia.FechaHora,
                Usuario = ic.incidencia.Usuario,
                CodOficina = ic.oficina.Codigo,
                NombreOficina = ic.oficina.Nombre,
                TipoDispositivo = ic.tipo.Titulo,
                ModeloDispositivo = ic.modelo.Marca + " " + ic.modelo.Modelo,
                Tecnico = ic.tecnico.NombreEmpresa,
                NumSerie = ic.dispositivo.NumeroSerie,
                Mensaje = ic.incidencia.Descripcion
            });

            var nombreArchivo = $"Averías-{anyo}.xlsx";

            return GenerarExcel(nombreArchivo, incidenciasExportar);


        }

        public async Task<FileResult> ExportarExcelAnyoSinDescripcion(string anyo)
        {
            int intAnyo = 0;
            int.TryParse(anyo, out intAnyo);

            var incidencias = await context.Incidencias.ToListAsync();
            var dispositivos = await context.Dispositivos.ToListAsync();
            var modelosDispositivos = await context.ModelosDispositivos.ToListAsync();
            var oficinas = await context.Oficinas.ToListAsync();
            var tecnicos = await context.Tecnicos.ToListAsync();
            var tiposDispositivos = await context.TiposDispositivos.ToListAsync();

            var incidenciasConsulta = from incidencia in incidencias
                                      join dispositivo in dispositivos on incidencia.DispositivoId equals dispositivo.Id
                                      join modelo in modelosDispositivos on dispositivo.ModeloDispositivoId equals modelo.Id
                                      join tipo in tiposDispositivos on modelo.TipoDispositivoId equals tipo.Id
                                      join oficina in oficinas on incidencia.OficinaId equals oficina.Id
                                      join tecnico in tecnicos on incidencia.TecnicoId equals tecnico.Id
                                      where incidencia.FechaHora.Year == intAnyo
                                      select new
                                      {
                                          incidencia,
                                          oficina,
                                          dispositivo,
                                          modelo,
                                          tipo,
                                          tecnico
                                      };

            var incidenciasExportar = incidenciasConsulta.Select(ic => new IncidenciaExportar()
            {
                Id = ic.incidencia.Id,

GestionIncidencias/Controllers/GraficosController.cs
namespace GestionIncidencias.Controllers
{
    public class GraficosController : Controller
    {
        private readonly ApplicationDbContext context;

        public GraficosController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> ObtenerIncidenciasGraficoLineas(DateTime start, DateTime end)
        {
            var incidencias = await context.Incidencias.ToListAsync();
            var dispositivos = await context.Dispositivos.ToListAsync();
            var modelosDispositivos = await context.ModelosDispositivos.ToListAsync();
            var tiposDispositivos = await context.TiposDispositivos.ToListAsync();

            List<ElementoGraficoLineas> incidenciasGrafico = new List<ElementoGraficoLineas>();

            foreach (TipoDispositivo tp in tiposDispositivos)
            {
                ElementoGraficoLineas elemento = new ElementoGraficoLineas();

                elemento.Label = tp.Titulo;
                elemento.BorderColor = Constantes.asignarColor(tp.Id);
                elemento.Fill = false;
                elemento.Tension = 0.1f;

                List<int> lista = new List<int>();

                for (DateTime fecha = start; fecha < end; fecha = fecha.AddMonths(1))
                {
                    var subconsulta = from incidencia in incidencias
                                      join dispositivo in dispositivos on incidencia.DispositivoId equals dispositivo.Id
                                      join modelo in modelosDispositivos on dispositivo.ModeloDispositivoId equals modelo.Id
                                      where incidencia.FechaHora > fecha.AddDays(-1) && incidencia.FechaHora < fecha.AddMonths(1) && incidencia.Activo == true && modelo.TipoDispositivoId == tp.Id
                                      select new
                                      {
                                          incidencia
                                      };
                    int resultado = subconsulta.Count();
                    lista.Add(resultado);
                }
                elemento.Data = lista.ToArray();

                incidenciasGrafico.Add(elemento);
            }

            return Json(incidenciasGrafico);
        }

        public async Task<JsonResult> ObtenerIncidenciasGraficoUsuarios()
        {
            var incidencias = await context.Incidencias.ToListAsync();
            var usuarios = await context.Users.ToListAsync();

            List<int> data = new List<int>(); // Cuenta de Incidencias por Usuario
            List<string> labels = new List<string>(); // Códigos de Usuarios
            List<string> backgroundColor = new List<string>();
            int contador = 6;

            foreach (IdentityUser usuario in usuarios)
            {
                var subconsulta = from incidencia in incidencias
                                  where incidencia.Usuario == usuario.UserName
                                  select new
                                  {
                                      incidencia
                                  };
                int resultado = subconsulta.Count();

                if (resultado > 0)
                {
                    data.Add(resultado);
                    labels.Add(usuario.UserName);
                    backgroundColor.Add(Constantes.asignarColor(contador));
                    contador++;
                }
            }

            DatosGraficoDonut datosGraficoDonut = new DatosGraficoDonut();
            datosGraficoDonut.Labels = labels.ToArray();
            DatasetDonut datasetDonut = new DatasetDonut();
            datasetDonut.Label = "Incidencias por Usuario";
            datasetDonut.Data = data.ToArray();
            datasetDonut.BackgroundColor = backgroundColor.ToArray();
            datosGraficoDonut.Datasets = (new DatasetDonut[] { datasetDonut }).ToArray();

            return Json(datosGraficoDonut);

        }

        public async Task<JsonResult> ObtenerIncidenciasGraficoOficinas()
        {
            var incidencias = await context.Incidencias.ToListAsync();
            var ubicaciones = await context.Oficinas.ToListAsync();


            List<Tuple<string, int, string>> elementos = new List<Tuple<string, int, string>>();
            // La primera posición es el nombre de la ubicación, la segunda la cantidad de incidencias y la tercera el color

            int contador = 9;

            foreach (Oficina oficina in ubicaciones)
            {
                var subconsulta = from incidencia in incidencias
                                  where incidencia.OficinaId == oficina.Id && incidencia.Activo == true
                                  select new
                                  {
                                      incidencia
                                  };
                int resultado = subconsulta.Count();

                elementos.Add(new Tuple<string, int, string>(oficina.Nombre, resultado, "#409B88"));
                contador++;
            }

            elementos.Sort((x, y) => y.Item2.CompareTo(x.Item2));
            elementos = elementos.Take(10).ToList();


            List<string> labels = new List<string>();
            List<int> data = new List<int>();
            List<string> backgroundColor = new List<string>();
           
            foreach (Tuple<string, int, string> elemento in elementos)
            {
                labels.Add(elemento.Item1);
                data.Add(elemento.Item2);
                backgroundColor.Add(elemento.Item3);
            }
            
            DatosGraficoDonut datosGraficoDonut = new DatosGraficoDonut();
            datosGraficoDonut.Labels = labels.ToArray();
            DatasetDonut datasetDonut = new DatasetDonut();
            datasetDonut.Data = data.ToArray();
            datasetDonut.BackgroundColor = backgroundColor.ToArray();
            datosGraficoDonut.Datasets = (new DatasetDonut[] { datasetDonut }).ToArray();

            return Json(datosGraficoDonut);

        }
    }
}

GestionIncidencias/Views/Home/Crear_Registrar.cshtml
@model Incidencia

@{
    ViewData["Title"] = "Nueva Avería";


    Oficina oficina = ViewBag.oficina;
    string oficinaId = (ViewBag.oficina != null ? ViewBag.oficina.Id.ToString() : "");

    Dispositivo dispositivo = ViewBag.dispositivo;
    string dispositivoId = (ViewBag.dispositivo != null ? ViewBag.dispositivo.Id.ToString() : "");

    Tecnico tecnico = ViewBag.tecnico;
    string tecnicoId = (ViewBag.tecnico != null ? ViewBag.tecnico.Id.ToString() : "");

    TipoDispositivo tipoDispositivo = ViewBag.tipoDispositivo;
    string tipoDispositivoId = (ViewBag.tipoDispositivo != null ? ViewBag.tipoDispositivo.Id.ToString() : "");

    ModeloDispositivo modeloDispositivo = ViewBag.modeloDispositivo;
    string modeloDispositivoId = (ViewBag.modeloDispositivo != null ? ViewBag.modeloDispositivo.Id.ToString() : "");

    string asunto = ViewBag.asunto ?? "";
    string texto = ViewBag.texto ?? "";
}

<h2>Crear Avería: Completar Datos</h2>

<div class="d-flex justify-content-evenly mb-2">
    <div class="d-flex mt-2 mb-2">
        <strong>Centro: </strong>&nbsp;@(Context.Request.Method == "GET" ? oficina.Codigo : "-")
    </div>
    <div class="d-flex mt-2 mb-2">
        <strong>Tipo: </strong>&nbsp;@(Context.Request.Method == "GET" ? tipoDispositivo.Titulo : "-")
    </div>
    <div class="d-flex mt-2 mb-2">
        <strong>Modelo: </strong>&nbsp;@(Context.Request.Method == "GET" ? modeloDispositivo.Marca + " - " + modeloDispositivo.Modelo : "-")
    </div>
    <div class="d-flex mt-2 mb-2">
        <strong>S/N: </strong>&nbsp;@(Context.Request.Method == "GET" ? dispositivo.NumeroSerie : "-")
    </div>
    <div class="d-flex mt-2 mb-2">
        <strong>Técnico: </strong>&nbsp;@(Context.Request.Method == "GET" ? tecnico.NombreEmpresa : "-")
    </div>
</div>

@* <h5>Detallar avería:</h5> *@

@*Animación de Carga*@
<div class="loading" align="center">
    <div class="hourglass"></div>
</div>

<div class="d-flex justify-content-center">
    <div style="width: 600px">
        <form id="miFormulario" asp-action="Crear_Registrar">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div style="display: none;">
                <div class="mb-3">
                    <label asp-for="FechaHora" class="form-label"></label>
                    <input id="fechaHora" asp-for="FechaHora" class="form-control" />
                    <span asp-validation-for="FechaHora" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Usuario" class="form-label"></label>
                    <input id="usuario" asp-for="Usuario" class="form-control" />
                    <span asp-validation-for="Usuario" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="OficinaId" class="form-label"></label>
                    <input id="oficinaId" asp-for="OficinaId" class="form-control" />
                    <span asp-validation-for="OficinaId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="DispositivoId" class="form-label"></label>
                    <input id="dispositivoId" asp-for="DispositivoId" class="form-control" />
                    <span asp-validation-for="DispositivoId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="TecnicoId" class="form-label"></label>
                    <input id="tecnicoId" asp-for="TecnicoId" class="form-control" />
                    <span asp-validation-for="TecnicoId" class="text-danger"></span>
                </div>
            </div>

            <p><span class="col-form-label"><strong>Asunto:</strong></span>&nbsp;<span class="form-control">@asunto</span></p>

            <div class="col-4">
                <strong><label asp-for="Descripcion"></label>:</strong>
            </div>
            <div class="col-8 mb-4">
                <textarea id="textDescripcion" style="width: 600px; height:250px;" asp-for="Descripcion" class="form-control">Insertar Texto Aquí</textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>

            <button class="btn btn-success" formmethod="post" onmousedown="ShowProgress()">Guardar</button>
            <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        
        var textDescripcion = document.getElementById('textDescripcion');
        var fechaHora = document.getElementById('fechaHora');
        var oficinaId = document.getElementById('oficinaId');
        var dispositivoId = document.getElementById('dispositivoId');
        var TecnicoId = document.getElementById('tecnicoId');
        var usuario = document.getElementById('usuario');
        // var hoy = new Date();
        // var dia = hoy.getFullYear() + '-' + hoy.getMonth() + '-' + hoy.getDay();

        window.onload = function () {
            // Si hay parámetros en la URL, es probable que sea una solicitud GET
            if (window.location.href.indexOf('?') !== -1) {
                textDescripcion.innerHTML = '@texto';
                fechaHora.value = '@DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")';
                oficinaId.value = '@oficinaId';
                dispositivoId.value = '@dispositivoId';
                TecnicoId.value = '@tecnicoId';
                usuario.value = '@User.Identity.Name';
            }
            setTimeout(function () {
                document.body.removeChild(modal);
                loading.style.display = "none";
            }, 100); //Poner a 1000 si se quiere aumentar el tiempo en un segundo.
        };

        
    </script>

}

GestionIncidencias/Views/Home/Crear_Seleccionar.cshtml
@model DispositivosListadoViewModel

@{
    ViewData["Title"] = "Seleccionar Dispositivo";
}

<h2>Crear Avería: Selección de Dispositivo</h2>
<h5 class="mt-2">Seleccionar Centro y Tipo de Dispositivo, después elegir de la lista.</h5>

@*Animación de Carga*@
<div class="loading" align="center">
    <div class="hourglass"></div>
</div>

@*Insertar aquí los select de Oficina y Tipo Dispositivo*@
<div class="d-flex justify-content-evenly">
    <div class="d-flex mt-2 mb-2">
        <label class="text-nowrap mt-1 me-2 form-label">Centro: </label>
        <select id="SelectCentro" asp-items="@(new SelectList(@ViewBag.SelectOficina,"Id","Codigo"))" class="form-select">
            <option disabled selected> -- Seleccione -- </option>
        </select>
        @* <select id="SelectCentro" class="form-select"></select> *@
    </div>
    <div class="d-flex mt-2 mb-2">
        <label class="text-nowrap mt-1 me-2 form-label">Tipo de Dispositivo:</label>
        <select id="SelectTipoDispositivo" asp-items="@(new SelectList(@ViewBag.SelectTiposDispositivos,"Id","Titulo"))" class="form-select">
            <option disabled selected> -- Seleccione -- </option>
        </select>
    </div>
    <div class="d-flex mt-2 mb-2">
        <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
    </div>
</div>

@if (Model.Dispositivos.Count > 0)
{
    <div id="seccionTablaDispositivosSelect">
        <table summary="Tabla Selección Dispositivo" id="tablaDispositivosSelect" class="table table-hover mt-2">
            <thead>
                <tr>
                    <th>Centro</th>
                    <th>Tipo Dispositivo</th>
                    <th>Marca y Modelo</th>
                    <th>Num. Serie</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dispositivo in Model.Dispositivos)
                {
                    <tr>
                        @{
                            List<TipoDispositivo> listaTiposDispositivos = ViewBag.SelectTiposDispositivos;
                            TipoDispositivo tipoDispositivo = listaTiposDispositivos.Where(td => td.Id == dispositivo.ModeloDispositivo.TipoDispositivoId).FirstOrDefault();
                        }

                        @{
                            var oficina = dispositivo.Oficina.Codigo + " - " + dispositivo.Oficina.Nombre;
                        }
                        <td>
                            @oficina
                        </td>
                        <td title="Descripción: @tipoDispositivo.Descripcion">
                            @tipoDispositivo.Titulo
                        </td>
                        <td title="Descripción: @dispositivo.ModeloDispositivo.Descripcion">
                            @dispositivo.ModeloDispositivo.Marca - @dispositivo.ModeloDispositivo.Modelo
                        </td>
                        <td>
                            @dispositivo.NumeroSerie
                        </td>

                        <td>
                            <button class="text-nowrap btn btn-sm btn-success me-2" onclick="crearRegistrar(@dispositivo.Id)">
                                Abir Avería
                            </button>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>

}
else
{
    <h3 class="mt-3">No se encontraron dispositivos</h3>
}

@section Scripts{
    <script>

        // DATATABLES Y SELECT

        // DataTables
        var tabla = new DataTable('#tablaDispositivosSelect', {
            language: {
                url: '/lib/data-tables/json/es-ES.json'
            },
            ordering: false,
            lengthChange: false
        });

        // Referenciamos los select
        var selectCentro = document.getElementById('SelectCentro');
        var selectTipoDispositivo = document.getElementById('SelectTipoDispositivo');
        var divTabla = document.getElementById('seccionTablaDispositivosSelect');

        // Eventos de cambio de valor
        selectCentro.addEventListener('change', function () {
            var texto = selectCentro.options[selectCentro.selectedIndex].text;
            console.log("Disparado cambio del selectCentro. Valor: " + selectCentro.value + ". Texto: " + texto);
            var centroSeleccionado = selectCentro.value;
            tabla.column(0).search(texto + '|' + '0000', true, false).draw();
        });
        selectTipoDispositivo.addEventListener('change', function () {
            var texto = selectTipoDispositivo.options[selectTipoDispositivo.selectedIndex].text;
            console.log("Disparado cambio del selectTipoDispositivo. Valor: " + selectTipoDispositivo.value);
            var tipoDispositivoSeleccionado = selectTipoDispositivo.value;
            tabla.column(1).search(texto).draw();
        });



        // PARA HACER EL POST HACIA Crear_Registrar crearIncidencia(dispositivo.Id)

        const urlCrearRegistrar = '@Url.Action("Crear_Registrar")';

        function crearRegistrar(dispositivoId) {
            if (selectCentro.options[selectCentro.selectedIndex].text != "-- Seleccione --") {
                var centroId = selectCentro.value;
                var tipoDispositivoId = selectTipoDispositivo.value;

                var nuevaURL = urlCrearRegistrar +
                    "?centroId=" + centroId +
                    "&dispositivoId=" + dispositivoId;

                window.location.href = nuevaURL;
            }
            else {
                toastr.error("Error, seleccione CENTRO");
            }
        }


        // RELOJ DE CARGA, PERO AÑADIENDO EN EL TIMING LA ACCION DE FILTRAR POR OFICINA

        window.onload = function () {
            setTimeout(function () {
                //Reloj
                document.body.removeChild(modal);
                loading.style.display = "none";
                // Filtrar por SelectCentro
                var texto = selectCentro.options[selectCentro.selectedIndex].text;
                //console.log("Disparado cambio del selectCentro. Valor: " + selectCentro.value + ". Texto: " + texto);
                var centroSeleccionado = selectCentro.value;
                tabla.column(0).search(texto + '|' + '0000', true, false).draw();
                // Filtrar por SelectTIpo
                var texto = selectTipoDispositivo.options[selectTipoDispositivo.selectedIndex].text;
                //console.log("Disparado cambio del selectTipoDispositivo. Valor: " + selectTipoDispositivo.value);
                var tipoDispositivoSeleccionado = selectTipoDispositivo.value;
                tabla.column(1).search(texto).draw();
                // Mostrar tabla al final del tiempo de espera
            }, 0); //Poner a 1000 si se quiere aumentar el tiempo en un segundo.
        };


    </script>
}

GestionIncidencias/Views/Home/NoEncontrado.cshtml
@{
    ViewData["Title"] = "No encontrado";
}

<h2 class="text-center m-3">ERROR</h2>
<h3 class="text-center m-3">No se ha encontrado el elemento especificado.</h3>

GestionIncidencias/Views/Home/_Submenu.cshtml
@model SubMenuIncidencias
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(Model == SubMenuIncidencias.Incidencias ? "btn btn-success" : "btn btn-secondary")"
                       asp-action="Index" asp-controller="Home">Lista</a>
                </li>
                <li class="nav-item">
                    <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(Model == SubMenuIncidencias.Calendario ? "btn btn-success" : "btn btn-secondary")"
                       asp-action="Index" asp-controller="Calendario">Calendario</a>
                </li>
                <li class="nav-item">
                    <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(Model == SubMenuIncidencias.Graficos ? "btn btn-success" : "btn btn-secondary")"
                       asp-action="Index" asp-controller="Graficos">Gráficos</a>
                </li>
                <li class="nav-item">
                    <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(Model == SubMenuIncidencias.Exportar ? "btn btn-success" : "btn btn-secondary")"
                       asp-action="Index" asp-controller="Exportar">Exportar</a>
                </li>
            </ul>
        </div>
    </div>
</nav>