GestionIncidencias/Controllers/OficinasController.cs
namespace GestionIncidencias.Controllers
{
    public class OficinasController: Controller
    {
        private readonly ApplicationDbContext context;

        public OficinasController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // Acción para el Index de Oficinas
        public async Task<IActionResult> Index(string mensaje = null)
        {
            var oficinas = await context.Oficinas.Select(o => new OficinaViewModel
            {
                Id = o.Id,
                Codigo = o.Codigo,
                Nombre = o.Nombre,
                Telefono = o.Telefono,
                Activado = o.Activo
            }).OrderByDescending(o => o.Activado).ThenBy(o => o.Codigo).ToListAsync();

            var modelo = new OficinasListadoViewModel();
            modelo.Oficinas = oficinas;
            modelo.Mensaje = mensaje;

            return View(modelo);
        }

        // Crear nueva Oficina
        [HttpGet]
        [Authorize(Roles = Constantes.RolAdmin)]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Crear(Oficina oficina)
        {
            if (!ModelState.IsValid)
            {
                return View(oficina);
            }

            oficina.Activo = true;

            await context.Oficinas.AddAsync(oficina);

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"La oficina o centro '{oficina.Codigo} - {oficina.Nombre}' se ha creado." });
        }


        // Acción de Activar Oficina
        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Activar(int id)
        {
            var oficina = await context.Oficinas.Where(o => o.Id == id).FirstOrDefaultAsync();

            if (oficina is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            oficina.Activo = true;

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"La oficina o centro '{oficina.Codigo} - {oficina.Nombre}' se ha activado." });
        }

        // Acción de Desactivar Oficina
        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Desactivar(int id)
        {
            var oficina = await context.Oficinas.Where(o => o.Id == id).FirstOrDefaultAsync();

            if (oficina is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            oficina.Activo = false;
            await context.SaveChangesAsync();
            return RedirectToAction("Index", routeValues: new { mensaje = $"La oficina o centro '{oficina.Codigo} - {oficina.Nombre}' se ha desactivado." });
        }

        // Editar Oficina

        [HttpGet]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Editar(int id)
        {

            Oficina oficina = await context.Oficinas.Where(o => o.Id == id).FirstOrDefaultAsync();

            if (oficina is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(oficina);
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Editar(Oficina oficina)
        {
            if (!ModelState.IsValid)
            {
                return View(oficina);
            }

            oficina.Activo = true;

            context.Oficinas.Update(oficina);

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"La oficina o centro '{oficina.Codigo} - {oficina.Nombre}' se ha modificado." });
        }

    }
}

GestionIncidencias/Controllers/TecnicosController.cs
namespace GestionIncidencias.Controllers
{
    public class TecnicosController: Controller
    {
        private readonly ApplicationDbContext context;

        public TecnicosController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // Accion para el Index de Técnicos
        public async Task<IActionResult> Index(string mensaje = null)
        {
            var tecnicos = await context.Tecnicos.Select(t => new TecnicoViewModel
            {
                Id = t.Id,
                NombreEmpresa = t.NombreEmpresa,
                CorreoElectronico = t.CorreoPara,
                Telefono = t.Telefono,
                Activado = t.Activo
            }).OrderByDescending(t => t.Activado).ThenBy(t => t.NombreEmpresa).ToListAsync();

            var modelo = new TecnicosListadoViewModel();
            modelo.Tecnicos = tecnicos;
            modelo.Mensaje = mensaje;

            return View(modelo);
        }

        // Acción de Activar Técnico
        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Activar(int id)
        {
            var tecnico = await context.Tecnicos.Where(t => t.Id == id).FirstOrDefaultAsync();

            if (tecnico is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            tecnico.Activo = true;

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"El servicio técnico '{tecnico.NombreEmpresa}' ha sido activado" });
        }

        // Acción de Desactivar Técnico
        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Desactivar(int id)
        {
            var tecnico = await context.Tecnicos.Where(t => t.Id == id).FirstOrDefaultAsync();

            if (tecnico is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            tecnico.Activo = false;

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"El servicio técnico '{tecnico.NombreEmpresa}' ha sido desactivado" });
        }

        // Crear nuevo Servicio Técnico
        [HttpGet]
        [Authorize(Roles = Constantes.RolAdmin)]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Crear(Tecnico tecnico)
        {
            if (!ModelState.IsValid)
            {
                return View(tecnico);
            }

            tecnico.Activo = true;

            await context.Tecnicos.AddAsync(tecnico);

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"El servicio técnico '{tecnico.NombreEmpresa}' ha sido creado" });
        }


        // Editar Servicio Técnico

        [HttpGet]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Editar(int id)
        {

            Tecnico tecnico = await context.Tecnicos.Where(t => t.Id == id).FirstOrDefaultAsync();

            if (tecnico is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(tecnico);
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Editar(Tecnico tecnico)
        {
            if (!ModelState.IsValid)
            {
                return View(tecnico);
            }

            tecnico.Activo = true;

            context.Tecnicos.Update(tecnico);

            await context.SaveChangesAsync();

            return RedirectToAction("Index", routeValues: new { mensaje = $"El servicio técnico '{tecnico.NombreEmpresa}' ha sido modificado" });
        }

    }
}

GestionIncidencias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionIncidencias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/loading/css/loading.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestionIncidencias.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/data-tables/css/cdn.datatables.net_1.13.6_css_jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/css/toastr.min.css" />
    @* <link rel="stylesheet" href="~/lib/sweetalert/css/sweetalert2.min.css"> *@
    @*Sección para las hojas de estilo*@
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body>
    <header>
        <nav class="mb-3 navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a style="font-size: xx-large; font-weight: bold;" class="navbar-brand" asp-controller="Home" asp-action="Index">
                    Gestión Averías <span style="font-size: medium; font-weight: normal;"
                                          title="@File.ReadAllText(AppContext.BaseDirectory + "NotasVersion.txt");">
                        @File.ReadLines(AppContext.BaseDirectory + "NotasVersion.txt").FirstOrDefault()
                    </span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(ViewContext.View.Path.Contains("/Home") ||
                                                                        ViewContext.View.Path.Contains("/Calendario") ||
                                                                        ViewContext.View.Path.Contains("/Exportar") ?
                                                                        "btn btn-success" : "btn btn-secondary")" asp-controller="Home" asp-action="Index">Avisos</a>
                        </li>

                        <li class="nav-item">
                            <strong>
                                <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(ViewContext.View.Path.Contains("/Dispositivos") ||
                                                                        ViewContext.View.Path.Contains("/TiposDispositivos") ||
                                                                        ViewContext.View.Path.Contains("/ModelosDispositivos") ?
                                                                        "btn btn-success" : "btn btn-secondary")"
                                   asp-controller="Dispositivos" asp-action="Index">Dispositivos</a>
                            </strong>
                        </li>

                        <li class="nav-item">
                            <strong>
                                <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(ViewContext.View.Path.Contains("/Tecnicos") ? "btn btn-success" : "btn btn-secondary")"
                                   asp-controller="Tecnicos" asp-action="Index">Técnicos</a>
                            </strong>
                        </li>

                        <li class="nav-item">
                            <strong>
                                <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(ViewContext.View.Path.Contains("/Oficinas") ? "btn btn-success" : "btn btn-secondary")"
                                   asp-controller="Oficinas" asp-action="Index">Oficinas</a>
                            </strong>
                        </li>

                        @if (User.IsInRole(Constantes.RolAdmin))
                        {
                            <li class="nav-item">
                                <strong>
                                    <a style="font-weight: bold; width: 120px;" class="ms-1 me-1 @(ViewContext.View.Path.Contains("/Usuarios") ? "btn btn-success" : "btn btn-secondary")"
                                       asp-controller="Usuarios" asp-action="Listado">Usuarios</a>
                                </strong>
                            </li>
                        }

                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2023 - Francisco Javier Sánchez Gragera
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/loading/js/loading.js" asp-append-version="true"></script>
    <script src="~/lib/data-tables/js/cdn.datatables.net_1.13.6_js_jquery.dataTables.min.js"></script>
    <script src="~/lib/data-tables/js/code.jquery.com_jquery-3.7.0.js"></script>
    <script src="~/lib/toastr/js/toastr.min.js"></script>
    @* <script src="~/lib/sweetalert/js/sweetalert2.all.min.js"></script> *@
    <script>
        toastr.options = {
            positionClass: 'toast-bottom-right', // Esta opción posiciona el mensaje en la esquina inferior derecha
            closeButton: false // Puedes mostrar un botón de cierre en el mensaje si lo deseas
        };

        // Refrescar Tabla al redimensionar ventana
        $(window).resize(function () {
            $(".sorting").width(""); //This is the class it sets to each < th >
            $(".tablaRedimensionable").width("100%"); //Class I set to the table for  this. An id won't work.
            $(".dataTables_scrollHeadInner").width("100%"); // Class of div added by DataTables, contains the header table.
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestionIncidencias/Views/Shared/_LinksLogin.cshtml
@inject SignInManager<IdentityUser> SignInManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-light">Hola @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-light">
                    <strong>Salir</strong>
                </button>
            </form>
        </li>
        <li class="nav-item">
            <a class="nav-link btn btn-link text-light" formmethod="get" asp-controller="Usuarios" asp-action="passwordOlvidado">
                <strong>Contraseña...</strong>
            </a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">
                <strong>Nuevo Usuario</strong>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">
                <strong>Iniciar Sesión</strong>
            </a>
        </li>
    }
</ul>